# Generated by Django 4.1.6 on 2023-02-22 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.BigIntegerField(default=0)),
                ('address', models.CharField(default='', max_length=150)),
                ('country', django_countries.fields.CountryField(max_length=50)),
                ('gender', models.CharField(default='None', max_length=50)),
                ('dob', models.DateField(default='', max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam'), ('Hindi', 'Hindi')], default='', max_length=50)),
                ('skills', models.CharField(choices=[('Django', 'Django'), ('Html', 'Html'), ('PHP', 'PHP'), ('Java', 'Java')], default='', max_length=50)),
                ('state', models.CharField(choices=[('kerala', 'kerala'), ('demo', 'demo'), ('None', 'None')], default='', max_length=50)),
                ('district', models.CharField(choices=[('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Kannur', 'Kannur'), ('Trivandrum', 'Trivandrum'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Idukki', 'Idukki'), ('Kollam', 'Kollam'), ('Ernakulam', 'Ernakulam'), ('Wayanad', 'Wayanad'), ('Kasaragod', 'Kasaragod'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('None', 'None')], default='', max_length=50)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='Profile')),
                ('Resume', models.FileField(blank=True, null=True, upload_to='Resume')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_company', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_employee', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=500)),
                ('s_level', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=500)),
                ('r_email', models.CharField(max_length=500)),
                ('r_phone', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=500)),
                ('lname', models.CharField(max_length=500)),
                ('mname', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=500)),
                ('dob', models.DateField(default='None')),
                ('bio', models.TextField()),
                ('avator', models.ImageField(default='profile/avator.png', null=True, upload_to='profile/')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobname', models.CharField(default='', max_length=250)),
                ('companyname', models.CharField(default='', max_length=250)),
                ('jobtype', models.CharField(choices=[('Part-Time', 'Part-Time'), ('Full-Time', 'Full-Time'), ('Internship', 'Internship')], default='', max_length=250)),
                ('category', models.CharField(choices=[('Web Developers', 'Web Developers'), ('Mobile Developers', 'Mobile Developers'), ('Designers & Creatives', 'Designers & Creatives'), ('Writers', 'Writers'), ('Virtual Assistants', 'Virtual Assistants'), ('Accountants & Consultants', 'Accountants & Consultants'), ('Sales & Marketing Experts', 'Sales & Marketing Experts'), ('Customer Service Agents', 'Customer Service Agents')], default='', max_length=250)),
                ('companyaddress', models.CharField(default='', max_length=250)),
                ('jobdescription', models.TextField(default='', max_length=1500)),
                ('qualification', models.TextField(default='', max_length=1500)),
                ('responsibility', models.TextField(default='', max_length=1500)),
                ('location', models.CharField(default='', max_length=250)),
                ('companywebsite', models.CharField(default='', max_length=20)),
                ('companycontact', models.BigIntegerField(default=0)),
                ('companyemail', models.EmailField(default='', max_length=50)),
                ('salarypackage', models.CharField(default='', max_length=40)),
                ('experience', models.CharField(default='', max_length=40)),
                ('logo', models.ImageField(default='', upload_to='logos')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_office', models.CharField(max_length=500)),
                ('e_position', models.CharField(max_length=500)),
                ('e_duration', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(default='', max_length=200)),
                ('minsalary', models.CharField(default='', max_length=20)),
                ('maxsalary', models.CharField(default='', max_length=20)),
                ('resume', models.FileField(upload_to='resume')),
                ('cand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.jobdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_institution', models.CharField(max_length=500)),
                ('a_year', models.CharField(max_length=500)),
                ('a_award', models.CharField(max_length=500)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
