# Generated by Django 3.1.7 on 2022-11-18 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jobname', models.CharField(default='', max_length=250)),
                ('companyname', models.CharField(default='', max_length=250)),
                ('companyaddress', models.CharField(default='', max_length=250)),
                ('jobdescription', models.TextField(default='', max_length=500)),
                ('qualification', models.CharField(default='', max_length=250)),
                ('responsibility', models.CharField(default='', max_length=250)),
                ('location', models.CharField(default='', max_length=250)),
                ('companywebsite', models.CharField(default='', max_length=20)),
                ('companycontact', models.BigIntegerField(default=0)),
                ('companyemail', models.EmailField(default='', max_length=50)),
                ('salarypackage', models.CharField(default='', max_length=40)),
                ('experience', models.IntegerField()),
                ('logo', models.ImageField(default='', upload_to='images/joppost/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
