# Generated by Django 3.1.7 on 2022-11-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_jobdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='email',
            new_name='userid',
        ),
    ]
