# Generated by Django 3.1.7 on 2022-11-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_auto_20221118_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='qualification',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='responsibility',
            field=models.CharField(default='', max_length=500),
        ),
    ]
