# Generated by Django 3.1.7 on 2022-11-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_auto_20221118_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='jobdescription',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='qualification',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='responsibility',
            field=models.CharField(default='', max_length=250),
        ),
    ]
