# Generated by Django 3.1.7 on 2022-11-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_auto_20221118_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(default='', upload_to='logos'),
        ),
    ]
