# Generated by Django 3.1.7 on 2022-11-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20221118_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='userid',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
    ]
