# Generated by Django 3.1.7 on 2022-11-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_auto_20221118_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='profile_pic',
            new_name='profilepic',
        ),
    ]
