# Generated by Django 3.1.7 on 2022-11-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_applylist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applylist',
            old_name='email',
            new_name='cand',
        ),
    ]
