# Generated by Django 3.1.7 on 2022-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20221120_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='experience',
            field=models.CharField(default='', max_length=40),
        ),
    ]
