# Generated by Django 3.1.7 on 2022-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_auto_20221120_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='jobtype',
            field=models.CharField(default='', max_length=250),
        ),
    ]
