# Generated by Django 3.1.7 on 2022-10-17 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_employee', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('job_title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=10)),
                ('last_date', models.DateTimeField()),
                ('SSLC_school', models.CharField(max_length=150)),
                ('SSLC_percentage', models.IntegerField()),
                ('High_school', models.CharField(max_length=150)),
                ('HighSchool_percentage', models.IntegerField()),
                ('UG', models.CharField(max_length=150)),
                ('UG_percentage', models.IntegerField()),
                ('PG', models.CharField(max_length=150)),
                ('PG_percentage', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('filled', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
