# Generated by Django 3.1.7 on 2022-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=200)),
                ('desp', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
