# Generated by Django 3.1.7 on 2022-11-18 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joblist',
        ),
    ]
