# Generated by Django 3.1.7 on 2022-10-27 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20221027_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblist',
            name='date',
            field=models.DateField(default=datetime.date(2022, 10, 28)),
        ),
    ]
