# Generated by Django 3.1.7 on 2022-11-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Resume',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_pic',
        ),
    ]
