# Generated by Django 3.1.7 on 2022-11-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_auto_20221104_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Files/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/Candidate/'),
        ),
    ]
