# Generated by Django 3.1.7 on 2022-11-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20221104_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=200)),
                ('desp', models.TextField()),
                ('companyname', models.CharField(max_length=250)),
            ],
        ),
    ]
