# Generated by Django 3.1.7 on 2022-11-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyJob',
        ),
        migrations.DeleteModel(
            name='JobListing',
        ),
    ]
